In [1]:
import nltk

In [3]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
stopwords = nltk.corpus.stopwords.words("english")

In [7]:
text = 'John is good in badminton. John play badminton. Badminton is a good game.'
words = nltk.word_tokenize(text)
print(words)
words = [w for w in words if w.lower() not in stopwords]
print(words)

['John', 'is', 'good', 'in', 'badminton', '.', 'John', 'play', 'badminton', '.', 'Badminton', 'is', 'a', 'good', 'game', '.']
['John', 'good', 'badminton', '.', 'John', 'play', 'badminton', '.', 'Badminton', 'good', 'game', '.']


In [8]:
fd = nltk.FreqDist(words)
print(fd.most_common(5))

[('.', 3), ('John', 2), ('good', 2), ('badminton', 2), ('play', 1)]


In [9]:
import nltk
nltk.download("stopwords")
arb_stopwords = set(nltk.corpus.stopwords.words("arabic"))
arb_stopwords


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


{'آه',
 'آها',
 'آي',
 'أف',
 'أقل',
 'أكثر',
 'ألا',
 'أم',
 'أما',
 'أن',
 'أنا',
 'أنت',
 'أنتم',
 'أنتما',
 'أنتن',
 'أنى',
 'أو',
 'أولئك',
 'أولاء',
 'أوه',
 'أي',
 'أين',
 'أينما',
 'أيها',
 'إذ',
 'إذا',
 'إذما',
 'إذن',
 'إلا',
 'إلى',
 'إليك',
 'إليكم',
 'إليكما',
 'إليكن',
 'إما',
 'إن',
 'إنا',
 'إنما',
 'إنه',
 'إي',
 'إيه',
 'التي',
 'الذي',
 'الذين',
 'اللائي',
 'اللاتي',
 'اللتان',
 'اللتيا',
 'اللتين',
 'اللذان',
 'اللذين',
 'اللواتي',
 'بخ',
 'بس',
 'بعد',
 'بعض',
 'بك',
 'بكم',
 'بكما',
 'بكن',
 'بل',
 'بلى',
 'بما',
 'بماذا',
 'بمن',
 'بنا',
 'به',
 'بها',
 'بهم',
 'بهما',
 'بهن',
 'بي',
 'بيد',
 'بين',
 'تلك',
 'تلكم',
 'تلكما',
 'ته',
 'تي',
 'تين',
 'تينك',
 'ثم',
 'ثمة',
 'حاشا',
 'حبذا',
 'حتى',
 'حيث',
 'حيثما',
 'حين',
 'خلا',
 'دون',
 'ذا',
 'ذات',
 'ذاك',
 'ذان',
 'ذانك',
 'ذلك',
 'ذلكم',
 'ذلكما',
 'ذلكن',
 'ذه',
 'ذو',
 'ذوا',
 'ذواتا',
 'ذواتي',
 'ذي',
 'ذين',
 'ذينك',
 'ريث',
 'سوف',
 'سوى',
 'شتان',
 'عدا',
 'عسى',
 'عل',
 'على',
 'عليك',
 'عليه',
 'عم

In [10]:
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
english_stopwords = set(stopwords.words('english'))
stop_words = set(stopwords.words('english')) - set(['again', 'once', 'from'])
stop_words

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


{'a',
 'about',
 'above',
 'after',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',


In [2]:
from nltk.corpus import names
nltk.download('names')
print("\nNumber of male names:")
print (len(names.words('male.txt')))
print("\nNumber of female names:")
print (len(names.words('female.txt')))


Number of male names:
2943

Number of female names:
5001


[nltk_data] Downloading package names to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package names is already up-to-date!


In [4]:
male_names = names.words('male.txt')
female_names = names.words('female.txt')
print("\nFirst 15 male names:")
print (male_names[0:15])
print("\nFirst 15 female names:")
print (female_names[0:15])


First 15 male names:
['Aamir', 'Aaron', 'Abbey', 'Abbie', 'Abbot', 'Abbott', 'Abby', 'Abdel', 'Abdul', 'Abdulkarim', 'Abdullah', 'Abe', 'Abel', 'Abelard', 'Abner']

First 15 female names:
['Abagael', 'Abagail', 'Abbe', 'Abbey', 'Abbi', 'Abbie', 'Abby', 'Abigael', 'Abigail', 'Abigale', 'Abra', 'Acacia', 'Ada', 'Adah', 'Adaline']


In [3]:
male_names = names.words('male.txt')
female_names = names.words('female.txt')

labelled_male_names = [(str(name), 'male') for name in male_names]
labelled_female_names = [(str(name), 'female') for name in female_names]

labelled_all_names = labelled_male_names + labelled_female_names
labelled_all_names

[('Aamir', 'male'),
 ('Aaron', 'male'),
 ('Abbey', 'male'),
 ('Abbie', 'male'),
 ('Abbot', 'male'),
 ('Abbott', 'male'),
 ('Abby', 'male'),
 ('Abdel', 'male'),
 ('Abdul', 'male'),
 ('Abdulkarim', 'male'),
 ('Abdullah', 'male'),
 ('Abe', 'male'),
 ('Abel', 'male'),
 ('Abelard', 'male'),
 ('Abner', 'male'),
 ('Abraham', 'male'),
 ('Abram', 'male'),
 ('Ace', 'male'),
 ('Adair', 'male'),
 ('Adam', 'male'),
 ('Adams', 'male'),
 ('Addie', 'male'),
 ('Adger', 'male'),
 ('Aditya', 'male'),
 ('Adlai', 'male'),
 ('Adnan', 'male'),
 ('Adolf', 'male'),
 ('Adolfo', 'male'),
 ('Adolph', 'male'),
 ('Adolphe', 'male'),
 ('Adolpho', 'male'),
 ('Adolphus', 'male'),
 ('Adrian', 'male'),
 ('Adrick', 'male'),
 ('Adrien', 'male'),
 ('Agamemnon', 'male'),
 ('Aguinaldo', 'male'),
 ('Aguste', 'male'),
 ('Agustin', 'male'),
 ('Aharon', 'male'),
 ('Ahmad', 'male'),
 ('Ahmed', 'male'),
 ('Ahmet', 'male'),
 ('Ajai', 'male'),
 ('Ajay', 'male'),
 ('Al', 'male'),
 ('Alaa', 'male'),
 ('Alain', 'male'),
 ('Alan', 'male

In [4]:
import random
random.shuffle(labelled_all_names)
print("Combined Names - ", labelled_all_names[:20])

Combined Names -  [('Annecorinne', 'female'), ('Sadella', 'female'), ('Burta', 'female'), ('Bea', 'female'), ('French', 'male'), ('Millicent', 'male'), ('Martino', 'male'), ('Kerrin', 'female'), ('Doug', 'male'), ('Berthe', 'female'), ('Bubba', 'male'), ('Lucie', 'female'), ('Deidre', 'female'), ('Lorrie', 'male'), ('Saudra', 'female'), ('Malcah', 'female'), ('Dulcine', 'female'), ('Valaree', 'female'), ('Melinda', 'female'), ('Dirk', 'male')]


In [12]:
from nltk.corpus import wordnet 
nltk.download('wordnet')
syns = wordnet.synsets("Education")
print("Defination of the said word:")
print(syns[0].definition())
print("\nExamples of the word in use::")
print(syns[0].examples())

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Defination of the said word:
the activities of educating or instructing; activities that impart knowledge or skill

Examples of the word in use::
['he received no formal education', 'our instruction was carefully programmed', 'good classroom teaching is seldom rewarded']


In [13]:
def jaccard_coef(x ,y ):
  x = list(x.split())
  y= list(y.split())
  intersection = len(list(set(x).intersection(y)))
  union = (len(x) + len(y)) - intersection
  return float(intersection) / union
ref = 'meet me at the airport tomorrow'
test = 'meat me at the aeroport 2morrw'
print("Jaccard Coefficient =" , jaccard_coef(ref , test))

Jaccard Coefficient = 0.3333333333333333


In [14]:
def edit_distance(s1, s2):
    m=len(s1)+1
    n=len(s2)+1

    tbl = {}
    for i in range(m): tbl[i,0]=i
    for j in range(n): tbl[0,j]=j
    for i in range(1, m):
        for j in range(1, n):
            cost = 0 if s1[i-1] == s2[j-1] else 1
            tbl[i,j] = min(tbl[i, j-1]+1, tbl[i-1, j]+1, tbl[i-1, j-1]+cost)

    return (tbl[i,j])
ref = 'meet me at the airport tomorrow'
test = 'meat me at the aeroport 2morrw'
ref = ref.split()
test = test.split()
print("Length of ref" , len(ref))
summ=0
for i in range(0 , 6):
  dist = edit_distance(ref[i] , test[i])
  print("Edit Distance of word" , i ,'=' , dist)
  summ = summ + dist
print("total correction =" , summ)
print("Average Correction Words= " , summ/len(ref))

Length of ref 6
Edit Distance of word 0 = 1
Edit Distance of word 1 = 0
Edit Distance of word 2 = 0
Edit Distance of word 3 = 0
Edit Distance of word 4 = 2
Edit Distance of word 5 = 3
total correction = 6
Average Correction Words=  1.0


In [15]:
# Cosine Similarity

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from nltk.corpus import stopwords
import numpy as np
import numpy.linalg as LA
import nltk
nltk.download('stopwords')

train_set = ["The sky is blue.", "The sun is bright."]  # Documents
test_set = ["The sun in the sky is bright."]  # Query
stopWords = stopwords.words('english')

vectorizer = CountVectorizer(stop_words = stopWords)
#print vectorizer
transformer = TfidfTransformer()
#print transformer

trainVectorizerArray = vectorizer.fit_transform(train_set).toarray()
testVectorizerArray = vectorizer.transform(test_set).toarray()
print ('Fit Vectorizer to train set', trainVectorizerArray)
print ('Transform Vectorizer to test set', testVectorizerArray)

transformer.fit(trainVectorizerArray)
print (transformer.transform(trainVectorizerArray).toarray())

transformer.fit(testVectorizerArray)
tfidf = transformer.transform(testVectorizerArray)
print(tfidf.todense())


Fit Vectorizer to train set [[1 0 1 0]
 [0 1 0 1]]
Transform Vectorizer to test set [[0 1 1 1]]
[[0.70710678 0.         0.70710678 0.        ]
 [0.         0.70710678 0.         0.70710678]]
[[0.         0.57735027 0.57735027 0.57735027]]


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [16]:
from nltk.corpus import wordnet

In [17]:
context_sentence='The river bank sloping land was full of dead fishes'
sent=context_sentence.split()
#print (sent)
context=set(sent)
print (context)

{'sloping', 'of', 'river', 'The', 'full', 'dead', 'land', 'bank', 'fishes', 'was'}


In [18]:
synsets = wordnet.synsets('bank')


In [19]:
for ss in synsets:
    print(ss,":",ss.definition())
#a=(ss.definition())
#a.split()

Synset('bank.n.01') : sloping land (especially the slope beside a body of water)
Synset('depository_financial_institution.n.01') : a financial institution that accepts deposits and channels the money into lending activities
Synset('bank.n.03') : a long ridge or pile
Synset('bank.n.04') : an arrangement of similar objects in a row or in tiers
Synset('bank.n.05') : a supply or stock held in reserve for future use (especially in emergencies)
Synset('bank.n.06') : the funds held by a gambling house or the dealer in some gambling games
Synset('bank.n.07') : a slope in the turn of a road or track; the outside is higher than the inside in order to reduce the effects of centrifugal force
Synset('savings_bank.n.02') : a container (usually with a slot in the top) for keeping money at home
Synset('bank.n.09') : a building in which the business of banking transacted
Synset('bank.n.10') : a flight maneuver; aircraft tips laterally about its longitudinal axis (especially in turning)
Synset('bank.v.0

In [20]:
sense=max((len(context.intersection(ss.definition().split())), ss) for ss in synsets)
print(sense)

(3, Synset('bank.n.01'))


In [23]:
from nltk.corpus import wordnet as wn 
from nltk.corpus import wordnet_ic
nltk.download('wordnet_ic')
brown_ic = wordnet_ic.ic('ic-brown.dat')
wn.synset('canine.n.02').path_similarity(wn.synset('canine.n.02'))

[nltk_data] Downloading package wordnet_ic to
[nltk_data]     C:\Users\devan\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet_ic is already up-to-date!


1.0

In [24]:
wn.synset('cardigan.n.2'). hypernyms()

[Synset('corgi.n.01')]

In [25]:
wn.synset('dog.n.01').hyponyms()

[Synset('basenji.n.01'),
 Synset('corgi.n.01'),
 Synset('cur.n.01'),
 Synset('dalmatian.n.02'),
 Synset('great_pyrenees.n.01'),
 Synset('griffon.n.02'),
 Synset('hunting_dog.n.01'),
 Synset('lapdog.n.01'),
 Synset('leonberg.n.01'),
 Synset('mexican_hairless.n.01'),
 Synset('newfoundland.n.01'),
 Synset('pooch.n.01'),
 Synset('poodle.n.01'),
 Synset('pug.n.01'),
 Synset('puppy.n.01'),
 Synset('spitz.n.01'),
 Synset('toy_dog.n.01'),
 Synset('working_dog.n.01')]

In [26]:
wn.synset('corgi.n.01').hyponyms()

[Synset('cardigan.n.02'), Synset('pembroke.n.01')]

In [27]:
syn1 = wn.synsets('hello')[0]
syn2 = wn.synsets('selling')[0]
syn1.path_similarity(syn2)

0.08333333333333333

In [28]:
syn1.lch_similarity(syn2)

1.1526795099383855

In [29]:
syn1.wup_similarity(syn2)

0.26666666666666666

In [30]:
syn1.res_similarity(syn2, ic=brown_ic)

0.5962292078977726

In [31]:
syn1.lin_similarity(syn2, ic=brown_ic)

0.06030388812056654

In [32]:
syn1.jcn_similarity(syn2, ic=brown_ic)

0.05381639985657784

In [33]:
sorted(syn1.common_hypernyms(syn2))

[Synset('abstraction.n.06'), Synset('entity.n.01')]

In [34]:
ref = syn1.hypernyms()[0]
print ("Self comprison : ", syn1.shortest_path_distance(ref))
print ("Distance of hello from greeting : ", syn1.shortest_path_distance(syn2))
print ("Distance of greeting from hello : ", syn2.shortest_path_distance(syn1))

Self comprison :  1
Distance of hello from greeting :  11
Distance of greeting from hello :  11
